version: "3"
services:
  mongodb-docker:
    image: mongo:latest
    container_name: "mongodb-docker"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-docker-app
    ports:
      - 8080:8080
    links:
      - mongodb-docker